### ISSUE TITLE
Can someone help implement continuous integration ?

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/tracker-enabled-dbcontext#54]

**Comment by Excommunicated** [comment]
I'd like to help. What do you need?

**Comment by Excommunicated** [comment]
Actually, I have done this in my fork.
Checkout https://github.com/Excommunicated/tracker-enabled-dbcontext/tree/appveyorIntegration to see what changes I had to make. I can provide you with whatever you might need to set this up for your project..

**Comment by bilal-fazlani** [comment]
I just saw branch. very good work implementing CI. And I liked appveyor.
I integrated it in just a couple of minutes. I had to disable the test run though because I don't any database hosted. 

I was going though the google search results and cant seem to find free MSMSQL hosting with even minimal features. The Azure basic tier also comes with a price.

But anyways, thanks for pointing me to appveyor :)

**Comment by Excommunicated** [comment]
I probably should have included some appveyor settings :)
appveyor offer sql instances for CI test running for free. They will always be a new instance so there is no prep or cleanup required.
I did make one critical change to the creation of the dbContexts in the test classes to work with this system. See line 11 of https://github.com/Excommunicated/tracker-enabled-dbcontext/blob/appveyorIntegration/TrackerEnabledDbContext.IntegrationTests/TestTrackerContext.cs
 and line 12 of https://github.com/Excommunicated/tracker-enabled-dbcontext/blob/appveyorIntegration/TrackerEnabledDbContext.Identity.IntegrationTests/TestTrackerIdentityContext%20.cs

anyways. This is my appveyor.yml, which is really really simple to get you started..
``` yaml
version: 2.7.{build}
environment:
  DefaultTestConnection: Server=(local)\SQL2014;Database=TrackerEnabledDbContextTests;User ID=sa;Password=Password12!
services: mssql2014
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
```
